# Generated by Django 2.1.3 on 2018-11-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Satellite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hwid", models.TextField(max_length=20, unique=True)),
                ("catid", models.TextField(blank=True, max_length=20)),
                ("tle1", models.TextField(blank=True, max_length=100)),
                ("tle2", models.TextField(blank=True, max_length=100)),
            ],
        )
    ]
