# Generated by Django 2.1.4 on 2018-12-10 08:55

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [("home", "0004_passes")]

    operations = [
        migrations.AlterField(
            model_name="groundstation", name="elevation", field=models.FloatField()
        ),
        migrations.AlterField(
            model_name="groundstation",
            name="hwid",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="groundstation", name="latitude", field=models.FloatField()
        ),
        migrations.AlterField(
            model_name="groundstation", name="longitude", field=models.FloatField()
        ),
        migrations.AlterField(
            model_name="pass",
            name="access_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pass", name="end_time", field=home.models.ISODateTimeField()
        ),
        migrations.AlterField(
            model_name="pass", name="start_time", field=home.models.ISODateTimeField()
        ),
    ]
