# Generated by Django 2.1.4 on 2018-12-10 09:00

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [("home", "0005_use_floats_and_isodatetime")]

    operations = [
        migrations.CreateModel(
            name="CachedAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket_hash", models.CharField(max_length=100)),
                ("start_time", home.models.ISODateTimeField(blank=True, null=True)),
                ("end_time", home.models.ISODateTimeField(blank=True, null=True)),
                ("modified", home.models.ISODateTimeField(auto_now=True)),
                ("max_alt", models.FloatField(blank=True, null=True)),
                ("placeholder", models.BooleanField(default=False)),
                (
                    "groundstation",
                    models.ForeignKey(
                        on_delete=False, to="home.GroundStation", to_field="hwid"
                    ),
                ),
                (
                    "satellite",
                    models.ForeignKey(
                        on_delete=False, to="home.Satellite", to_field="hwid"
                    ),
                ),
            ],
        )
    ]
