# Generated by Django 2.1.4 on 2018-12-19 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("home", "0006_cachedaccess")]

    operations = [
        migrations.AlterField(
            model_name="cachedaccess",
            name="groundstation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="home.GroundStation",
                to_field="hwid",
            ),
        ),
        migrations.AlterField(
            model_name="cachedaccess",
            name="satellite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="home.Satellite",
                to_field="hwid",
            ),
        ),
    ]
