# Generated by Django 2.1.4 on 2018-12-19 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_auto_20181219_0049"),
        ("home", "0007_auto_20181219_0048"),
    ]

    operations = []
