# Generated by Django 2.1.4 on 2019-01-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_pass_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundstation',
            name='passes_read_only',
            field=models.BooleanField(default=False),
        ),
    ]
