# Generated by Django 2.1.4 on 2019-01-14 03:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_groundstation_passes_read_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='logger_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
