# Generated by Django 2.1.4 on 2019-01-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("home", "0015_task_stack")]

    operations = [
        migrations.AlterModelOptions(
            name="groundstation", options={"verbose_name_plural": "Groundstations"}
        ),
        migrations.AlterModelOptions(
            name="pass", options={"verbose_name_plural": "Passes"}
        ),
    ]
