# Generated by Django 2.1.4 on 2019-01-22 02:37

import django.contrib.postgres.fields.hstore
from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_verbose_plural_names'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='pass',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
