# Generated by Django 2.1.4 on 2019-01-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0017_pass_attributes")]

    operations = [
        migrations.AddField(
            model_name="taskstack",
            name="pinned",
            field=models.BooleanField(default=False),
        )
    ]
