# Generated by Django 2.1.4 on 2019-01-23 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("home", "0018_taskstack_pinned")]

    operations = [
        migrations.AlterField(
            model_name="pass",
            name="groundstation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="home.GroundStation",
                to_field="hwid",
            ),
        ),
        migrations.AlterField(
            model_name="pass",
            name="satellite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="home.Satellite",
                to_field="hwid",
            ),
        ),
        migrations.AlterField(
            model_name="pass",
            name="task_stack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.TaskStack",
                to_field="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="task_stack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.TaskStack",
                to_field="uuid",
            ),
        ),
    ]
