# Generated by Django 2.1.4 on 2019-01-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_taskstack_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='script',
        ),
    ]
