# Generated by Django 2.1.4 on 2019-01-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_auto_20190123_0605"),
        ("home", "0019_remove_pass_script"),
    ]

    operations = []
