# Generated by Django 2.1.4 on 2019-03-04 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_merge_20190124_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=128, unique=True)),
                ('what', models.TextField()),
                ('where', models.TextField()),
                ('path', models.TextField(blank=True, null=True)),
                ('start', home.models.ISODateTimeField(default=django.utils.timezone.now, help_text='The time of the first event in the file. If instantaneous, set this and leave end as null')),
                ('end', home.models.ISODateTimeField(blank=True, help_text='The time of the last event in the file. Can be blank if instantaneous file.', null=True)),
                ('created', home.models.ISODateTimeField(auto_now_add=True)),
            ],
            bases=(models.Model, home.models.Serializable),
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('task', models.TextField()),
                ('start_time', home.models.ISODateTimeField()),
                ('end_time', home.models.ISODateTimeField()),
                ('exit_code', models.IntegerField()),
                ('task_pass', models.ForeignKey(db_column='pass', on_delete=django.db.models.deletion.PROTECT, to='home.Pass', to_field='uuid')),
                ('task_stack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.TaskStack', to_field='uuid')),
            ],
            bases=(models.Model, home.models.Serializable),
        ),
        migrations.AddField(
            model_name='s3file',
            name='task_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='home.TaskRun', to_field='uuid'),
        ),
    ]
