# Generated by Django 2.1.7 on 2019-03-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_merge_20190124_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='celery_task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
