# Generated by Django 2.1.4 on 2019-03-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190304_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3file',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='s3file',
            name='work_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='s3file',
            name='task_run',
        ),
        migrations.AlterUniqueTogether(
            name='s3file',
            unique_together={('version', 'what', 'where', 'work_id')},
        ),
    ]
