# Generated by Django 2.1.4 on 2019-03-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190306_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s3file',
            options={'ordering': ('-version',)},
        ),
        migrations.AlterField(
            model_name='s3file',
            name='work_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
