# Generated by Django 2.1.7 on 2019-03-20 06:35

import datalake.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatalakeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('cid', models.CharField(max_length=33)),
                ('what', models.TextField()),
                ('where', models.TextField()),
                ('path', models.TextField(blank=True, null=True)),
                ('start', datalake.models.ISODateTimeField(default=django.utils.timezone.now, help_text='The time of the first event in the file. If instantaneous, set this and leave end as null')),
                ('end', datalake.models.ISODateTimeField(blank=True, help_text='The time of the last event in the file. Can be blank if instantaneous file.', null=True)),
                ('created', datalake.models.ISODateTimeField(auto_now_add=True)),
                ('work_id', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(choices=[(1, 1)])),
            ],
            options={'get_latest_by': ('start', 'created'), 'ordering': ('-start', 'created')},
            bases=(models.Model, datalake.models.Serializable),
        ),
        migrations.CreateModel(
            name='RelatedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(max_length=256)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='What',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=128, unique=True)),
            ],
            bases=(models.Model, datalake.models.Serializable),
        ),
        migrations.AddField(
            model_name='datalakefile',
            name='_related_to',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalake.RelatedFile'),
        ),
    ]
