#!/usr/bin/env bash

set -o errexit
set -o pipefail

export POSTGRES_USER="${POSTGRES_USER:=postgres}"
export BUILT_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
export DATABASE_URL="${DATABASE_URL:=$BUILT_URL}"

set -o nounset

postgres_ready() {
pipenv run python << END
import sys

import psycopg2

try:
    psycopg2.connect("${DATABASE_URL}")
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
