#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

# Might as well do this in the background while we wait for
# the frontend to compile
poetry run ./manage.py getephem &

poetry run python /app/manage.py collectstatic --noinput
poetry run gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
